### PR TITLE
Issue69 highlighter browser exception

### PR DESCRIPTION
**Pull request by onebenclark**
This branch fixes bugs found by Jenna. I implemented fixes and haven't gotten the exceptions thrown before.

### CODE REVIEW

**Comment by jennalwise** [comment]
Problems found when testing, see testing documentation in master branch docs file folder.

**Comment by onebenclark** [comment]
I cannot replicate the bug as it's described. Are there any other details of the setup?

**Comment by jennalwise** [comment]
Here are the steps of the trial/set-up:

Launch Eclipse application with iTrace controller
Open iTrace java source code file
Check the Highlight button (SystemMouseTracker is the tracking being used)
Move mouse around on source code

Other than that there isn't anything out of the ordinary or default.
I also started tracking and then hit the highlight button, but it still didn't work.

**Comment by onebenclark** [comment]
Is the file in the workspace?

**Comment by jennalwise** [comment]
Yes

**Comment by onebenclark** [comment]
I should asked this sooner but does the highlighter work on other branches?

**Pull request merged**
