### PR TITLE
Issue 2

### PR DESCRIPTION
**Pull request by trshaffer**
I merged my old code for detecting gazes on non-editor components and updated it to fit the current interfaces. Unfortunately, Eclipse doesn't like my window manager, so I can't test things. @jennalwise should try this out and see if it works

### CODE REVIEW

**Comment by relrod** [comment]
> Unfortunately, Eclipse doesn't like my window manager

A Java GUI doesn't work right in Xmonad? Say it ain't so!

**Comment by jennalwise** [comment]
@trshaffer I will get on testing it! Thanks for merging everything as well!

**Comment by shbonita** [comment]
@trshaffer How does the raw export show gazes on non-editor components? In particular, what would be the response record if we looked at the project outline view?  

I tested this and found  no gazes are registering if we look at project outline view which is mainly what we are interested in at this time.

**Comment by trshaffer** [comment]
It *should* be generating gazes with `type` set to `"part"`, and of course no SCE data. If nothing at all is coming through, the failure is likely to be in `GazeHandlerFactory.java` or `WorkbenchPartGazeHandler.java`. Maybe add some logging statements to see if it's successfully binding the handler, what the handler is doing, etc.

**Comment by shbonita** [comment]
This is Jenna's report. 
I found that a file that is open when we close the running application (i.e. the file is saved in the workspace when the running eclipse application is closed) will only be considered an IEditorReference if the file was in view when eclipse was closed. Otherwise, it is considered an IViewReference the next time the application is run.

If a file is not an IEditorReference, then a SCE Gaze Handler will not be created for it. 

The fix for this is to make sure that we exit all open files when running a new eclipse application. Once we reopen them they will become an IEditorReference and a SCE Gaze Handler will be created for the file.

Now I am still not sure how to fix the Project Explorer. I believe it has something to do with visibility of the Part Reference and the visibilities of other Part Reference's at the same time. 

This issue is not yet resolved.

**Comment by jennalwise** [comment]
I think now that it has something to do with the threading (a race condition more specifically), I just didn't send you an update about it because I wasn't going to look into it until after finals.

**Comment by onebenclark** [comment]
Ben will test this.

**Comment by onebenclark** [comment]
I just realized that this pull request isn't actually comparing our issue2 branch and master. It's comparing Tim's iTrace master branch to SERESL's master. It doesn't seem I can change that, so I'll open a new pull request that has the correct settings. Our branch shouldn't have any conflicts.

**Pull request closed without merging**
